@host = http://localhost:3020
@fileId = 662d6205cac7998bce449c75

# Upload  file
POST {{host}}/api/files/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="file.png"

< ./file.png

--boundary--

###

# Get file by ID
GET {{host}}/api/files/{{fileId}} HTTP/1.1

###
