services:
  readme.content-management.postgres:
    image: postgres:16.2
    restart: always
    container_name: readme-content-management_postgresDb

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - readme-content-management_data:/data/db
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  readme-content-management_data:
