services:
  readme.notification-management.fakesmtp:
    image: gessnerfl/fake-smtp-server:2.2.1
    container_name: "readme-notification-management.fakesmtp"
    restart: always

    hostname: "readme.notification.fakesmtp"
    ports:
      - ${SERVER_SMTP_PORT}:8025
      - ${SERVER_SMTP_PORT_UI}:8080

  readme.notification-management.rabbitmq:
    image: rabbitmq:3.13.1-management
    container_name: readme.notification-management.rabbitmq
    restart: always

    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_PORT_UI}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  readme.notification-management.mongo:
    image: mongo:7.0.8
    restart: always
    container_name: readme-notification-management_mongoDb

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - readme-notification-management_data:/data/db

volumes:
  readme-notification-management_data:
