services:
  readme.file-management.mongo:
    image: mongo:7.0.8
    restart: always
    container_name: readme-file-management_mongoDb

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - readme-file-management_data:/data/db
    networks:
      - readme-file-management.network

  readme.file-management.app:
    image: ghcr.io/opifexm/readme/file-management-app:latest
    container_name: readme-file-management_app
    depends_on:
      - readme.file-management.mongo
    restart: always

    env_file:
      - file-app.env
    ports:
      - ${APP_PORT}:3000
    networks:
      - readme-file-management.network

networks:
  readme-file-management.network:
    driver: bridge

volumes:
  readme-file-management_data:
