services:
  readme.file-management.mongo:
    image: mongo:7.0.8
    restart: always
    container_name: readme-file-management_mongoDb

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - readme-file-management_data:/data/db

volumes:
  readme-file-management_data:
