name: Node CI
on:
  - push
  - pull_request
env:
  CI: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4

      - name: Change directory to project
        run: cd project

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: project/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./project
